import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:google_fonts/google_fonts.dart';
import 'core/theme/aurora_theme.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase for the 2026 Flutter/Firebase stack
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    // ProviderScope is essential for Riverpod state management
    const ProviderScope(
      child: IntentionalApp(),
    ),
  );
}

class IntentionalApp extends StatelessWidget {
  const IntentionalApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Intentional',
      debugShowCheckedModeBanner: false,
      theme: AuroraTheme.lightTheme,
      // We will create the Dashboard view next
      home: const Scaffold(
        body: Center(child: Text('Intentional: Ground Up Build')),
      ),
    );
  }
}